## Configuracion de Spring
spring:
  application:
    name: ms-books-catalogue
  jackson:
    date-format: yyyy-MM-dd
    serialization:
      write-dates-as-timestamps: false
  datasource:
    url: jdbc:mysql://yamanote.proxy.rlwy.net:16171/railway
    username: root
    password: AYXMTmRmbmeKsJYXCNDzXPWegMpzNNTS
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true

  sql:
    init:
      mode: always   # Permite inicializar datos en la base de datos



## Configuracion de Instancia
server:
  port: 8090

## Configuracion del cliente de Eureka
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://spring-cloud-eureka-production-d206.up.railway.app:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: ms-books-catalogue


